project:
  type: website

website:
  title: "Jack's Way"
  navbar:
    right:
      #- about.qmd
      - icon: github
        href: https://github.com/jackbhuber/blog
    background: navy
    foreground: white

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

