project:
  type: website

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jackbhuber/Blog

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

