---
title: "We need better data to study deconstruction"
author: "Jack Huber"
date: "2022-08-12"
categories: [faith, deconstruction, data]
---

## Leaving Evangelicalism

I'm a religious person. I have identified as Christian, in one way or another, all my life.

I grew up in a Christian home. My parents identified as Christians, and they passed on to me Christianity as they understood it. On many Sunday mornings we went to church. My mother watched religious television. We frequented Christian bookstores. I listened to Christian music, and for a couple of years I attended a Christian private school. Several years later, in high school, I belonged to my church's youth group. As a result, many of my high school friends were Christians. It was a Christian world.

We didn't care where we fit in the broader world of Christianity. We claimed no affiliation to any broader denominations like the Baptists or the Presbyterians, we attended "nondenominational" churches. We simply thought of ourselves as "Christians." The sociological term that now describes that world is "conservative Protestant Evangelicals."

I pretty much left that world thirty years ago. In college I quit attending my family's Evangelical megachurch and have avoided others like it ever since. Aspects of that religious training proved poor preparation. Various beliefs seemed less credible to me. College vastly broadened my horizons. Part of my exit was social. In graduate school I came into contact and formed relationships with people from different backgrounds who held very different beliefs. The term that has come define that state or process of critically examining and in most cases letting go of those religious practices and beliefs is "deconstruction."

## Deconstruction

In the past thirty years, deconstruction has become a thing. There are myriad Facebook groups devoted "ex-Evangelicalism" or "post-Evangelicalism." There are influencers on Twitter and TikTok. There are numerous podcasts dedicated to critical examination of many different aspects of organized religion and theology. There are books about deconstruction. There are numerous articles on websites and print publications.

I don't like the term "deconstruction" because it seems to me one of those terms that means so many different things it means nothing in particular. People use the term differently. Like conversion stories, everyone has their own deconstruction story. Some are stories of being abused by clergy. Many others are accounts of disillusionment with their church's, denomination's or tradition's endorsement of the Donald Trump presidency or right-wing politics. It does seem to be primarily cognitive, referring to a cognitive process of withdrawing credence in one or more religious beliefs, doctrines, theological premises, biblical hermeneutics, or applications of these things to conservative politics. Like the evolving language surrounding the LGBTQ+ community, it might be functioning as an umbrella term to a phenomenon that has many different dimensions and manifestations. It might make sense to think of it as an identity.
